version: 1.0.{build}
configuration:
- Debug
- Release
- Mono
before_build:
- cmd: dotnet restore
after_build:
- ps: if($env:configuration -eq "Release") {dotnet pack ConsoleAppCore4}
build:
  verbosity: minimal
